services:
  test_app_1:
    environment:
      - PYTHONUNBUFFERED=1
      - APP_NAME=App1
    restart: always
    container_name: test_app_1
    build: test_app/
    image: test_app:latest
    expose:
       - 50051
    ports:
      - 50051:50051
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    container_name: nginx_test
    depends_on:
      - test_app_1
    ports:
      - "80:80"
      - "7000:7000"